### ISSUE TITLE
April 23 - Nan not found

### ISSUE THREAD

**Issue by dring1** [iojs/nan#320]
With the latest update to `nan` running into `nan` module not found. 

```
14:48:29 > node-gyp rebuild
14:48:29 
14:48:29 [91m
14:48:29 module.js:340
14:48:29     throw err;
14:48:29           ^
14:48:29 Error: Cannot find module 'nan'
14:48:29     at Function.Module._resolveFilename (module.js:338:15)
14:48:29     at Function.Module._load (module.js:280:25)
14:48:29     at Module.require (module.js:364:17)
14:48:29     at require (module.js:380:17)
14:48:29     at [eval]:1:1
14:48:29     at Object.<anonymous> ([eval]-wrapper:6:22)
14:48:29     at Module._compile (module.js:456:26)
14:48:29     at evalScript (node.js:565:25)
14:48:29     at startup (node.js:80:7)
14:48:29     at node.js:935:3
14:48:29 [0m[91mgyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
``

**Comment by jlai** [comment]
Looks like another instance of include_dirs.js getting lost by npm publish: #262 

```
$ curl -s https://registry.npmjs.org/nan/-/nan-1.8.1.tgz | tar ztvf -| grep include_dirs.js
$
```

**Comment by kkoopa** [comment]
Yup. I'll republish in an hour. Don't know why this keeps happening. Could there be a bug in npm?

**Comment by bengl** [comment]
Looks like it could be this one? https://github.com/npm/npm/issues/5082

**Comment by kkoopa** [comment]
Republished as 1.8.2.
```shell
~/dev/nan$ curl -s https://registry.npmjs.org/nan/-/nan-1.8.2.tgz | tar ztvf -| grep include_dirs.js
-rw-rw-r-- 1000/1000        55 2014-11-06 20:43 package/include_dirs.js
```

**Comment by kumavis** [comment]
:dragon_face: :+1:

**Comment by kkoopa** [comment]
@bengl Thanks, that seems like the right bug.
